### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Tester inscription API
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "first_name": "Louis",
  "last_name": "Legrand",
  "email": "legrand@example.com",
  "password": "secret123"
}

### API LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "olivier@example.com",
  "password": "tonMotDePasse"
}
